# Generated by Django 3.2.3 on 2021-06-14 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50, verbose_name='שם פריט')),
                ('manufacturer_id', models.CharField(max_length=50, verbose_name='מספר יצרן')),
                ('AF_id', models.CharField(max_length=50, verbose_name='מסח"א')),
                ('measurement_device_id', models.CharField(max_length=16, verbose_name="מס' סידורי של מכשיר הבדיקה")),
                ('calibration_date', models.DateField(default=django.utils.timezone.now, verbose_name='תאריך כיול אחרון')),
                ('expiration_date', models.DateField(verbose_name='בתוקף עד')),
            ],
        ),
    ]
