# Generated by Django 3.2.3 on 2021-06-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_device_calibration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementdevice',
            name='device_name',
        ),
    ]
