# Generated by Django 3.2.3 on 2021-06-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_device_calibration', '0003_measurementdevice_device_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurementdevice',
            old_name='measurement_device_id',
            new_name='device_id',
        ),
    ]
