# Generated by Django 3.2.2 on 2021-05-24 10:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.IntegerField(choices=[(1, 'כנף 1'), (2, 'כנף 4'), (3, 'בח"א 8'), (4, 'כנף 25'), (5, 'בח"א 28'), (6, 'בח"א 30'), (7, 'מחלקת שפיצים'), (8, 'מחלקת מנועים'), (9, 'מחלקת הנדסה')], verbose_name='מחלקה')),
                ('test_date', models.DateField(verbose_name='תאריך ביצוע הבדיקה')),
                ('test_time_start', models.TimeField(verbose_name='שעת תחילת הבדיקה')),
                ('test_time_end', models.TimeField(verbose_name='שעת סיום הבדיקה')),
                ('test_location', models.IntegerField(choices=[(1, 'מעבדה'), (2, 'גף תחזוקה'), (3, 'דת"ק/מוסך'), (4, 'אחר')], verbose_name='מקום ביצוע הבדיקה')),
                ('part_description', models.CharField(max_length=50, verbose_name='תיאור פריט')),
                ('part_id', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='[0-9]')], verbose_name="מס' סידורי של הפריט")),
                ('number_of_parts', models.IntegerField(default=1, verbose_name='מספר פריטים בבדיקה')),
                ('aircraft', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='[0-9]')], verbose_name='כלי טייס/מכלול')),
                ('aircraft_id', models.CharField(max_length=50, verbose_name="מס' זנב/סידורי")),
                ('test_method', models.IntegerField(choices=[(1, 'בדיקת ראיה'), (2, 'בדיקת הקשה'), (3, 'זרמי ערבולת'), (4, 'נוזלים חודרים'), (5, 'חלקיקים מגנטיים'), (6, 'אולטרסאונד'), (7, 'רדיוגרפיה'), (8, 'תרמוגרפיה'), (9, 'שירוגרפיה'), (10, 'אחר')], verbose_name='שיטת בדיקה')),
                ('testing_hours', models.FloatField(verbose_name='שעתון בדיקה')),
                ('findings', models.TextField(blank=True, verbose_name='ממצאים')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(default='', max_length=50)),
                ('rank', models.IntegerField(choices=[(1, "טור'"), (2, 'רב"ט'), (3, 'סמל'), (4, 'סמ"ר'), (5, 'רס"ל'), (6, 'רס"ר'), (7, 'רס"מ'), (8, 'רס"ב'), (9, 'רנ"ג')], default=1)),
                ('personal_number', models.CharField(default='0000000', max_length=7, validators=[django.core.validators.RegexValidator(regex='\\d{7}')])),
                ('level', models.IntegerField(choices=[(1, '5'), (2, '7'), (3, '9'), (4, '11'), (5, '12')], default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
