# Generated by Django 3.2.3 on 2021-06-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='EC_level',
            field=models.IntegerField(choices=[(1, 'אין הסמכה'), (2, 'רמה 1'), (3, 'רמה 2')], default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='MT_level',
            field=models.IntegerField(choices=[(1, 'אין הסמכה'), (2, 'רמה 1'), (3, 'רמה 2')], default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='PT_level',
            field=models.IntegerField(choices=[(1, 'אין הסמכה'), (2, 'רמה 1'), (3, 'רמה 2')], default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='UT_level',
            field=models.IntegerField(choices=[(1, 'אין הסמכה'), (2, 'רמה 1'), (3, 'רמה 2')], default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.IntegerField(choices=[(1, 'כנף 1'), (2, 'כנף 4'), (3, 'בח"א 8'), (4, 'כנף 25'), (5, 'בח"א 28'), (6, 'בח"א 30'), (7, 'מחלקת שפיצים'), (8, 'מחלקת מנועים'), (9, 'מחלקת הנדסה')], default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
