# Generated by Django 3.2.2 on 2021-05-24 13:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='checker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checker', related_query_name='checker', to='main.user', verbose_name='בודק'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='tag_number',
            field=models.IntegerField(blank=True, default=1, verbose_name='מספר תג תהליך בדיקת אל הרס'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='tester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tester', related_query_name='tester', to='main.user', verbose_name='מבצע'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_number',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(regex='\\d{7}')]),
        ),
    ]
