# Generated by Django 3.2.3 on 2021-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210615_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='IRT_level',
            field=models.IntegerField(choices=[(1, 'אין הסמכה'), (2, 'רמה 1'), (3, 'רמה 2')], default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='LST_level',
            field=models.IntegerField(choices=[(1, 'אין הסמכה'), (2, 'רמה 1'), (3, 'רמה 2')], default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='PAUT_level',
            field=models.IntegerField(choices=[(1, 'אין הסמכה'), (2, 'רמה 1'), (3, 'רמה 2')], default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='RT_level',
            field=models.IntegerField(choices=[(1, 'אין הסמכה'), (2, 'רמה 1'), (3, 'רמה 2')], default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='tap_level',
            field=models.IntegerField(choices=[(1, 'אין הסמכה'), (2, 'רמה 1'), (3, 'רמה 2')], default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='visual_level',
            field=models.IntegerField(choices=[(1, 'אין הסמכה'), (2, 'רמה 1'), (3, 'רמה 2')], default=2),
        ),
    ]
