# Generated by Django 3.2.2 on 2021-05-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210524_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_description', models.CharField(max_length=50, verbose_name='תיאור פריט')),
                ('test_method', models.IntegerField(choices=[(1, 'בדיקת ראיה'), (2, 'בדיקת הקשה'), (3, 'זרמי ערבולת'), (4, 'נוזלים חודרים'), (5, 'חלקיקים מגנטיים'), (6, 'אולטרסאונד'), (7, 'רדיוגרפיה'), (8, 'תרמוגרפיה'), (9, 'שירוגרפיה'), (10, 'אחר')], verbose_name='שיטת בדיקה')),
                ('testing_hours', models.FloatField(verbose_name='שעתון בדיקה')),
            ],
        ),
    ]
