# Generated by Django 3.2.2 on 2021-05-26 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='literature_code',
            field=models.CharField(default='00.00.00.00', max_length=50, verbose_name='שיוך לספרות טכנית'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer_id',
            field=models.CharField(default='000', max_length=50, validators=[django.core.validators.RegexValidator(regex='[0-9]')], verbose_name='מספר יצרן'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='literature_code',
            field=models.CharField(default='00.00.00.00', max_length=50, verbose_name='שיוך לספרות טכנית'),
            preserve_default=False,
        ),
    ]
