# Generated by Django 3.2.2 on 2021-05-31 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210526_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='meter_id',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='[0-9]')], verbose_name="מס' סידורי של מכשיר הבדיקה"),
        ),
        migrations.AlterField(
            model_name='test',
            name='findings',
            field=models.IntegerField(blank=True, choices=[(1, 'שמיש'), (2, 'סדוק'), (3, 'אחר'), (4, 'ראה הערות'), (5, 'נדרשת בדיקה נוספת')], verbose_name='ממצאים'),
        ),
        migrations.AlterField(
            model_name='test',
            name='notes',
            field=models.CharField(blank=True, max_length=50, verbose_name='הערות'),
        ),
    ]
