# Generated by Django 3.2.2 on 2021-05-31 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210531_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='aircraft',
            field=models.CharField(max_length=50, verbose_name='כלי טייס/מכלול'),
        ),
        migrations.AlterField(
            model_name='test',
            name='tag_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='[0-9]')], verbose_name='מספר תג תהליך בדיקת אל הרס'),
        ),
    ]
