# Generated by Django 3.2.3 on 2021-06-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210601_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='literature_code',
        ),
        migrations.RemoveField(
            model_name='test',
            name='manufacturer_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='part_description',
        ),
        migrations.RemoveField(
            model_name='test',
            name='part_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='tag_number',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_method',
        ),
        migrations.RemoveField(
            model_name='test',
            name='testing_hours',
        ),
        migrations.AddField(
            model_name='test',
            name='parts',
            field=models.ManyToManyField(to='main.TestItem'),
        ),
    ]
