# Generated by Django 3.2.3 on 2021-06-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210602_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='parts',
        ),
        migrations.AddField(
            model_name='testitem',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.test'),
            preserve_default=False,
        ),
    ]
