# Generated by Django 3.2.3 on 2021-06-03 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210602_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='item_id',
            field=models.CharField(default=1, max_length=50, verbose_name='מספר סידורי'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testitem',
            name='tag_number',
            field=models.CharField(default=1, max_length=50, verbose_name='מספר תג תהליך'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='number_of_parts',
            field=models.IntegerField(default=1, verbose_name='מספר פריטים'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='תאריך הבדיקה'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_location',
            field=models.IntegerField(choices=[(1, 'מעבדה'), (2, 'גף תחזוקה'), (3, 'דת"ק/מוסך'), (4, 'אחר')], verbose_name='מקום הבדיקה'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_time_end',
            field=models.TimeField(verbose_name='שעת סיום'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_time_start',
            field=models.TimeField(verbose_name='שעת התחלה'),
        ),
    ]
