# Generated by Django 3.2.3 on 2021-06-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210603_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='number_of_parts',
        ),
        migrations.AddField(
            model_name='testitem',
            name='number_of_parts',
            field=models.IntegerField(default=1, verbose_name='מספר פריטים'),
        ),
    ]
