# Generated by Django 3.2.3 on 2021-06-08 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210603_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='findings',
            field=models.IntegerField(choices=[(1, 'שמיש'), (2, 'סדוק'), (3, 'אחר'), (4, 'ראה הערות'), (5, 'נדרשת בדיקה נוספת')], verbose_name='ממצאים'),
        ),
        migrations.AlterField(
            model_name='test',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tester', related_query_name='tester', to=settings.AUTH_USER_MODEL, verbose_name='מבצע'),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='item_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='מספר סידורי'),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='number_of_parts',
            field=models.IntegerField(verbose_name='מספר פריטים'),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='tag_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='מספר תג תהליך'),
        ),
    ]
