# Generated by Django 3.2.3 on 2021-06-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210608_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferanceItem',
            new_name='ReferenceItem',
        ),
        migrations.AlterField(
            model_name='test',
            name='department',
            field=models.IntegerField(choices=[(1, 'כנף 1'), (2, 'כנף 4'), (3, 'בח"א 8'), (4, 'כנף 25'), (5, 'בח"א 28'), (6, 'בח"א 30'), (7, 'מחלקת שפיצים'), (8, 'מחלקת מנועים'), (9, 'מחלקת הנדסה')], verbose_name='שיוך ארגוני'),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.test'),
        ),
    ]
